import { ProjectRecord } from "./types";

export const demoProjects: ProjectRecord[] = [
  {
    "Project Name": "Online Banking Face Recognition",
    "Owner Div": "DIGITAL CHANNELS",
    "Type Project": "Project Utama",
    "Last Status": "Live",
    "Year": 2024,
    "Period": "Mar-24",
    "Kuartal": "Q1",
    "Reschedule UAT": null,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "5 (Telat Ringan)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Not Achieved",
    "Live SLA": "Achieved",
    "Rata-rata Nilai Feedback User : ": 4.8,
    "PIC Name": "Budi Santoso",
    "Owner Name": "Rian Wijaya"
  },
  {
    "Project Name": "QRIS Merchant Sandbox integration",
    "Owner Div": "CONSUMER BANKING",
    "Type Project": "Enhance Kecil",
    "Last Status": "Live On Monitoring",
    "Year": 2025,
    "Period": "Jan-25",
    "Kuartal": "Q1",
    "Reschedule UAT": 2,
    "(Dev) Late Days": "15 (Telat Parah > 14 Hari)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "10 (Telat Sedang 4-14 Hari)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Not Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Not Achieved",
    "Live SLA": "Achieved",
    "Rata-rata Nilai Feedback User : ": 4.5,
    "PIC Name": "Budi Santoso",
    "Owner Name": "Siti Rahma"
  },
  {
    "Project Name": "E-Commerce Gateway Upgrade V3",
    "Owner Div": "DIGITAL CHANNELS",
    "Type Project": "Hold Enhance Kecil", // Group 5: Enhance Kecil
    "Last Status": "Hold",
    "Year": 2025,
    "Period": "Feb-25",
    "Kuartal": "Q1",
    "Reschedule UAT": null,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "3 (Telat Ringan)",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Not Achieved",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": 4.1,
    "PIC Name": "Dewi Lestari",
    "Owner Name": "Andi Pratama"
  },
  {
    "Project Name": "Corporate Loan Mobile Flow",
    "Owner Div": "CORPORATE SEC.",
    "Type Project": "Project Utama",
    "Last Status": "Dev On Queue", // On Queue
    "Year": 2025,
    "Period": "Mar-25",
    "Kuartal": "Q1",
    "Reschedule UAT": 1,
    "(Dev) Late Days": null,
    "(FSD) Late Days": "8 (Telat Sedang 4-14 Hari)",
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Not Achieved",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Andik Wijaya",
    "Owner Name": "Dewi Lestari"
  },
  {
    "Project Name": "Risk Analytics Engine V2",
    "Owner Div": "RISK MANAGEMENT",
    "Type Project": "Approval Digital",
    "Last Status": "Live On Monitoring",
    "Year": 2025,
    "Period": "May-25",
    "Kuartal": "Q2",
    "Reschedule UAT": null,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Achieved",
    "Live SLA": "Achieved",
    "Rata-rata Nilai Feedback User : ": 4.9,
    "PIC Name": "Hendra Wijaya",
    "Owner Name": "Robby Hartono"
  },
  {
    "Project Name": "Customer Verification Suite",
    "Owner Div": "RISK MANAGEMENT",
    "Type Project": "Approval Digital",
    "Last Status": "UAT On Queue", // On Queue
    "Year": 2025,
    "Period": "May-25",
    "Kuartal": "Q2",
    "Reschedule UAT": 3,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": 4.4,
    "PIC Name": "Hendra Wijaya",
    "Owner Name": "Robby Hartono"
  },
  {
    "Project Name": "SME Credit Scoring API",
    "Owner Div": "CONSUMER BANKING",
    "Type Project": "Antrian Project Utama", // Group 5: Project Utama
    "Last Status": "On Queue", // On Queue
    "Year": 2025,
    "Period": "Jul-25",
    "Kuartal": "Q3",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": "4 (Telat Sedang 4-14 Hari)",
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Not Achieved",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Dewi Lestari",
    "Owner Name": "Budi Santoso"
  },
  {
    "Project Name": "Biometric Core Integration",
    "Owner Div": "CONSUMER BANKING",
    "Type Project": "Project Utama",
    "Last Status": "Live On Queue", // On Queue
    "Year": 2025,
    "Period": "Jul-25",
    "Kuartal": "Q3",
    "Reschedule UAT": 1,
    "(Dev) Late Days": "24 (Telat Parah > 14 Hari)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "18 (Telat Parah > 14 Hari)",
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Not Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Not Achieved",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Budi Santoso",
    "Owner Name": "Siti Rahma"
  },
  {
    "Project Name": "Internal IT Helpdesk Platform",
    "Owner Div": "INFORMATION TECHNOLOGY", // Should be automatically excluded!
    "Type Project": "Internal IT", // Should be automatically excluded!
    "Last Status": "Live",
    "Year": 2025,
    "Period": "Jan-25",
    "Kuartal": "Q1",
    "Reschedule UAT": null,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Achieved",
    "Live SLA": "Achieved",
    "Rata-rata Nilai Feedback User : ": 4.8,
    "PIC Name": "Feri Setiawan",
    "Owner Name": "Andik Wijaya"
  },
  {
    "Project Name": "Merchant Auto-Settlement Engine",
    "Owner Div": "DIGITAL CHANNELS",
    "Type Project": "Antrian Enhance Kecil", // Group 5: Enhance Kecil
    "Last Status": "On Progress",
    "Year": 2024,
    "Period": "Nov-24",
    "Kuartal": "Q4",
    "Reschedule UAT": 4,
    "(Dev) Late Days": "12 (Telat Sedang 4-14 Hari)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "5 (Telat Sedang 4-14 Hari)",
    "(UAT) Late Days": "18 (Telat Parah > 14 Hari)",
    "Live (Late Days)": null,
    "DEV SLA": "Not Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Not Achieved",
    "UAT SLA": "Not Achieved",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": 4.3,
    "PIC Name": "Andik Wijaya",
    "Owner Name": "Siti Rahma"
  },
  {
    "Project Name": "Wealth Management Onboarding API",
    "Owner Div": "CONSUMER BANKING",
    "Type Project": "Project Utama",
    "Last Status": "On Queue", // On Queue (Last Status containing "Queue")
    "Year": 2026,
    "Period": "Jan-26",
    "Kuartal": "Q1",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Achieved",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Siti Aminah",
    "Owner Name": "Robby Hartono"
  },
  {
    "Project Name": "Digital Token Autopay Setup",
    "Owner Div": "DIGITAL CHANNELS",
    "Type Project": "Enhance Kecil",
    "Last Status": "Live",
    "Year": 2026,
    "Period": "Feb-26",
    "Kuartal": "Q1",
    "Reschedule UAT": 1,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "4 (Telat Sedang 4-14 Hari)",
    "Live (Late Days)": "5 (Telat Sedang 4-14 Hari)",
    "DEV SLA": "Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Not Achieved",
    "Live SLA": "Not Achieved",
    "Rata-rata Nilai Feedback User : ": 4.7,
    "PIC Name": "Budi Santoso",
    "Owner Name": "Dewi Lestari"
  },
  {
    "Project Name": "Regulation Compliance Audit Flow",
    "Owner Div": "RISK MANAGEMENT",
    "Type Project": "Approval Digital",
    "Last Status": "LiveOnQueue", // Note: Let's make sure it has Queue inside if we want it to count, or "Live On Queue"
    "Year": 2026,
    "Period": "Feb-26",
    "Kuartal": "Q1",
    "Reschedule UAT": null,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Achieved",
    "Live SLA": "Achieved",
    "Rata-rata Nilai Feedback User : ": 4.9,
    "PIC Name": "Hendra Wijaya",
    "Owner Name": "Robby Hartono"
  },
  {
    "Project Name": "Secure Multi-Sign Authentication",
    "Owner Div": "CORPORATE SEC.",
    "Type Project": "Approval Digital",
    "Last Status": "Live",
    "Year": 2025,
    "Period": "Jun-25",
    "Kuartal": "Q2",
    "Reschedule UAT": null,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Achieved",
    "Live SLA": "Achieved",
    "Rata-rata Nilai Feedback User : ": 4.6,
    "PIC Name": "Siti Aminah",
    "Owner Name": "Andi Pratama"
  },
  {
    "Project Name": "Core Service Patch IT88",
    "Owner Div": "INFORMATION TECHNOLOGY", // Excluded div
    "Type Project": "Internal Patch",
    "Last Status": "Canceled",
    "Year": 2024,
    "Period": "Jan-24",
    "Kuartal": "Q1",
    "Reschedule UAT": null,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": null,
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Achieved",
    "FSD SLA": "Without",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Feri Setiawan",
    "Owner Name": "Rian Wijaya"
  },
  {
    "Project Name": "Lobby Queue Display System",
    "Owner Div": "CONSUMER BANKING",
    "Type Project": "Enhance Kecil",
    "Last Status": "Dev On Queue", // On Queue
    "Year": 2024,
    "Period": "Nov-24",
    "Kuartal": "Q4",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": "12 (Telat Sedang 4-14 Hari)",
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Not Achieved",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Andik Wijaya",
    "Owner Name": "Andi Pratama"
  },
  {
    "Project Name": "Salary Disbursement Scheduler",
    "Owner Div": "CORPORATE SEC.",
    "Type Project": "Approval Digital",
    "Last Status": "Live On Monitoring",
    "Year": 2024,
    "Period": "Dec-24",
    "Kuartal": "Q4",
    "Reschedule UAT": 2,
    "(Dev) Late Days": "0 (Tepat Waktu)",
    "(FSD) Late Days": "3 (Telat Ringan)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "14 (Telat Sedang 4-14 Hari)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Achieved",
    "FSD SLA": "Not Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Not Achieved",
    "Live SLA": "Achieved",
    "Rata-rata Nilai Feedback User : ": 4.4,
    "PIC Name": "Siti Aminah",
    "Owner Name": "Dewi Lestari"
  },
  {
    "Project Name": "Mobile App Dark Theme Layout",
    "Owner Div": "DIGITAL CHANNELS",
    "Type Project": "Enhance Kecil",
    "Last Status": "Canceled",
    "Year": 2025,
    "Period": "Aug-25",
    "Kuartal": "Q3",
    "Reschedule UAT": null,
    "(Dev) Late Days": "5 (Telat Sedang 4-14 Hari)",
    "(FSD) Late Days": "0 (Tepat Waktu)",
    "(SIT) Late Days": "0 (Tepat Waktu)",
    "(UAT) Late Days": "0 (Tepat Waktu)",
    "Live (Late Days)": "0 (Tepat Waktu)",
    "DEV SLA": "Not Achieved",
    "FSD SLA": "Achieved",
    "SIT SLA": "Achieved",
    "UAT SLA": "Achieved",
    "Live SLA": "Achieved",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Andik Wijaya",
    "Owner Name": "Dean Hartono"
  },
  {
    "Project Name": "Mobile App Biometric Login",
    "Owner Div": "DIGITAL CHANNELS",
    "Type Project": "Project Utama",
    "Last Status": "On Queue",
    "Year": null,
    "Period": null,
    "Kuartal": "Q1",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": null,
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Without",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Fajar Utama",
    "Owner Name": "Rian Wijaya"
  },
  {
    "Project Name": "Merchant Portal Revamp",
    "Owner Div": "CONSUMER BANKING",
    "Type Project": "Enhance Kecil",
    "Last Status": "Dev On Queue",
    "Year": null,
    "Period": null,
    "Kuartal": "Q2",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": null,
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Without",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Siti Aminah",
    "Owner Name": "Dean Hartono"
  },
  {
    "Project Name": "Database Index Optimization",
    "Owner Div": "DIGITAL CHANNELS",
    "Type Project": "Enhance Kecil",
    "Last Status": "Hold By IT",
    "Year": null,
    "Period": null,
    "Kuartal": "Q2",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": null,
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Without",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Budiman",
    "Owner Name": "Siti Rahma"
  },
  {
    "Project Name": "Automated End-to-End Tests",
    "Owner Div": "CORPORATE SEC.",
    "Type Project": "Project Utama",
    "Last Status": "UAT On Queue",
    "Year": null,
    "Period": null,
    "Kuartal": "Q3",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": null,
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Without",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Andik Wijaya",
    "Owner Name": "Andi Pratama"
  },
  {
    "Project Name": "Core Ledger Performance Tuning",
    "Owner Div": "CONSUMER BANKING",
    "Type Project": "Project Utama",
    "Last Status": "Live On Queue",
    "Year": null,
    "Period": null,
    "Kuartal": "Q3",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": null,
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Without",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Lisa Siregar",
    "Owner Name": "Siti Rahma"
  },
  {
    "Project Name": "FPS API Integration",
    "Owner Div": "DIGITAL CHANNELS",
    "Type Project": "Approval Digital",
    "Last Status": "FPS",
    "Year": null,
    "Period": null,
    "Kuartal": "Q4",
    "Reschedule UAT": null,
    "(Dev) Late Days": null,
    "(FSD) Late Days": null,
    "(SIT) Late Days": null,
    "(UAT) Late Days": null,
    "Live (Late Days)": null,
    "DEV SLA": "Without",
    "FSD SLA": "Without",
    "SIT SLA": "Without",
    "UAT SLA": "Without",
    "Live SLA": "Without",
    "Rata-rata Nilai Feedback User : ": null,
    "PIC Name": "Budi Santoso",
    "Owner Name": "Andi Pratama"
  }
];
